config/routes.rb
Rails.application.routes.draw do
  resources :cameras
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/phones" => "phones#index"

  get "/phones/new" => "phones#new"

  get "/phones/:id" => "phones#show"

  post "/phones" => "phones#create"

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/camera.rb
class Camera < ApplicationRecord
end

app/models/phone.rb
class Phone < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cameras_controller.rb
class CamerasController < ApplicationController
  before_action :set_camera, only: %i[ show edit update destroy ]

  # GET /cameras or /cameras.json
  def index
    @cameras = Camera.all
  end

  # GET /cameras/1 or /cameras/1.json
  def show
  end

  # GET /cameras/new
  def new
    @camera = Camera.new
  end

  # GET /cameras/1/edit
  def edit
  end

  # POST /cameras or /cameras.json
  def create
    @camera = Camera.new(camera_params)

    respond_to do |format|
      if @camera.save
        format.html { redirect_to @camera, notice: "Camera was successfully created." }
        format.json { render :show, status: :created, location: @camera }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @camera.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cameras/1 or /cameras/1.json
  def update
    respond_to do |format|
      if @camera.update(camera_params)
        format.html { redirect_to @camera, notice: "Camera was successfully updated." }
        format.json { render :show, status: :ok, location: @camera }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @camera.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cameras/1 or /cameras/1.json
  def destroy
    @camera.destroy
    respond_to do |format|
      format.html { redirect_to cameras_url, notice: "Camera was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_camera
      @camera = Camera.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def camera_params
      params.require(:camera).permit(:megapixels, :lense_size, :description)
    end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController

  def index
    @phones = Phone.all
    render 'index.html.erb'
  end

  def show
    @phone = Phone.find_by(id: params[:id])
    render 'show.html.erb'
  end

  def create
    @phone = Phone.new(
      name: params[:name],
      version: params[:version],
      color: params[:color]
    )
    @phone.save
    redirect_to "/phones/#{@phone.id}"
  end

  def new
    render 'new.html.erb'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/cameras/_form.html.erb
<%= form_with(model: camera) do |form| %>
  <% if camera.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(camera.errors.count, "error") %> prohibited this camera from being saved:</h2>

      <ul>
        <% camera.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :megapixels %>
    <%= form.number_field :megapixels %>
  </div>

  <div class="field">
    <%= form.label :lense_size %>
    <%= form.number_field :lense_size %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cameras/edit.html.erb
<h1>Editing Camera</h1>

<%= render 'form', camera: @camera %>

<%= link_to 'Show', @camera %> |
<%= link_to 'Back', cameras_path %>

app/views/cameras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cameras</h1>

<table>
  <thead>
    <tr>
      <th>Megapixels</th>
      <th>Lense size</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cameras.each do |camera| %>
      <tr>
        <td><%= camera.megapixels %></td>
        <td><%= camera.lense_size %></td>
        <td><%= camera.description %></td>
        <td><%= link_to 'Show', camera %></td>
        <td><%= link_to 'Edit', edit_camera_path(camera) %></td>
        <td><%= link_to 'Destroy', camera, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Camera', new_camera_path %>

app/views/cameras/new.html.erb
<h1>New Camera</h1>

<%= render 'form', camera: @camera %>

<%= link_to 'Back', cameras_path %>

app/views/cameras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Megapixels:</strong>
  <%= @camera.megapixels %>
</p>

<p>
  <strong>Lense size:</strong>
  <%= @camera.lense_size %>
</p>

<p>
  <strong>Description:</strong>
  <%= @camera.description %>
</p>

<%= link_to 'Edit', edit_camera_path(@camera) %> |
<%= link_to 'Back', cameras_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhonesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <a href="/phones">Home Page</a> |
    <a href="/phones/new">Add Phone</a>
    <%= yield %>
  </body>
</html>

app/views/phones/index.html.erb
<h1>Phone Index</h1>

<% @phones.each do |phone| %>
  
  <p><a href="http://localhost:3000/phones/<%= phone.id%>">Phone:</a> <%= phone.name %> </p>
  <p> Version: <%= phone.version %> </p>
  <p> Color: <%= phone.color %> </p>
  <hr>
<% end %>

app/views/phones/new.html.erb
<p>Add a new phone below:</p>

<%= form_tag "/phones", method: :post do %>
 <p>Phone: <input type="text" name="name"></p>
 <p>Version (Number): <input type="text" name="version"></p>
 <p>Color: <input type="text" name="color"></p>
 <p><input type="submit" value="Make a new phone:"></p>
<% end %>

app/views/phones/show.html.erb
<h1>I am in the phone show</h1>

  <p> Phone: <%= @phone.name %> </p>
  <p> Version: <%= @phone.version %> </p>
  <p> Color: <%= @phone.color %> </p>